[package]
name = "cargo-quad"
version = "0.1.0"
authors = ["Fedor Logachev <not.fl3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo = "0.61.1"
devserver_lib = "0.4"
fs_extra = "1.2"
